[package]
name = "enumscribe"
version = "0.1.0"
authors = ["Tom Panton <pantonshire@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Procedural macros for converting between enums and strings"

[dependencies]
enumscribe_derive = { path = "../enumscribe_derive" }
